services:
  kintone-mcp-server-public:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "80:80"
    environment:
      # Required Kintone configuration
      KINTONE_BASE_URL: ${KINTONE_BASE_URL}
      KINTONE_USERNAME: ${KINTONE_USERNAME:-}
      KINTONE_PASSWORD: ${KINTONE_PASSWORD:-}
      KINTONE_API_TOKEN: ${KINTONE_API_TOKEN:-}
      
      # Optional Basic Auth
      KINTONE_BASIC_AUTH_USERNAME: ${KINTONE_BASIC_AUTH_USERNAME:-}
      KINTONE_BASIC_AUTH_PASSWORD: ${KINTONE_BASIC_AUTH_PASSWORD:-}
      
      # Optional client certificate
      KINTONE_PFX_FILE_PATH: ${KINTONE_PFX_FILE_PATH:-}
      KINTONE_PFX_FILE_PASSWORD: ${KINTONE_PFX_FILE_PASSWORD:-}
      
      # Optional proxy
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      
      # Public HTTP server configuration  
      HOST: 0.0.0.0
      PORT: 80
      CORS_ORIGIN: "*"
      NODE_ENV: ${NODE_ENV:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - public
    # Security: Only allow specific IPs if needed
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - NET_BIND_SERVICE

networks:
  public:
    driver: bridge